[package]
name = "bare-necessities"
version = "0.1.0"
authors = ["Julien Vehent <julien@vehent.org>"]
edition = "2018"

[dependencies]
actix-web = "1.0.8"
diesel = { version = "1.4.6", features = ["postgres"] }
diesel_migrations = "1.4.0"
dotenv = "0.9.0"